//
//  testConfigurator.swift
//  CISample
//
//  Created by faifo on 5/5/16.
//  Copyright (c) 2016 od. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension testViewController: testPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension testInteractor: testViewControllerOutput
{
}

extension testPresenter: testInteractorOutput
{
}

class testConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: testConfigurator
  {
    struct Static {
      static var instance: testConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = testConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: testViewController)
  {
    let router = testRouter()
    router.viewController = viewController
    
    let presenter = testPresenter()
    presenter.output = viewController
    
    let interactor = testInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
