//
//  testPresenter.swift
//  CISample
//
//  Created by faifo on 5/5/16.
//  Copyright (c) 2016 od. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol testPresenterInput
{
  func presentSomething(response: testResponse)
}

protocol testPresenterOutput: class
{
  func displaySomething(viewModel: testViewModel)
}

class testPresenter: testPresenterInput
{
  weak var output: testPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: testResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = testViewModel()
    output.displaySomething(viewModel)
  }
}
