//
//  testInteractor.swift
//  CISample
//
//  Created by faifo on 5/5/16.
//  Copyright (c) 2016 od. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol testInteractorInput
{
  func doSomething(request: testRequest)
}

protocol testInteractorOutput
{
  func presentSomething(response: testResponse)
}

class testInteractor: testInteractorInput
{
  var output: testInteractorOutput!
  var worker: testWorker!
  
  // MARK: Business logic
  
  func doSomething(request: testRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = testWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = testResponse()
    output.presentSomething(response)
  }
}
